data: {
  features_columns: [
      ["Gait - Lower Limb - Cadence L (steps/min) [mean]", "Turns - Steps in Turn (#) [std]"],
    ],
  target_column: 2-minute Walk  (m),
  train_fraction: 0.7,
  random_state: 3,
}


neural_network: {
  model: None,
  spread: 6,
  depth: 5,
  activation: relu,

  optimizer: 
  {
      name: Adam,
      LR: 0.1,
      epoch: 1000,
  },

  quality: 
  {
      loss: mse,
      metrics: [mae, mse],
  }
}
